// File: data.js

const dataBranch = [
    "Medan", "Palembang", "Yogyakarta", "Surabaya", "Denpasar", "Balikpapan", 
    "Sentani", "Pontianak", "Banda Aceh", "Pekanbaru", "Tanjung Pinang", 
    "Halim", "Bandung", "Semarang", "Banjarmasin", "Palangkaraya", "Tarakan", 
    "Manado", "Kendari", "Lombok", "Kupang", "Ambon", "Wamena", "Nabire", 
    "Sorong", "Merauke", "Pusat Informasi Aeronautika"
];

const dataSubBranch = [
    "Palu", "Luwuk", "Gunung Sitoli", "Pangkal Pinang", "Jambi", "Banyuwangi", 
    "Malang", "Sumenep", "Labuan Bajo", "Samarinda", "Berau", "Biak", "Oksibil", 
    "Timika", "Ketapang", "Bengkulu", "Solo", "Rengat", "Padang", "Curug", 
    "Cirebon", "Pangkalan Bun", "Sampit", "Malinau", "Ternate", "Gorontalo", 
    "Bima", "Sumbawa", "Ende", "Tual, Karel Sadsuitubun", "Manokwari", 
    "Tanah Merah", "Batam", "Natuna"
];

const dataAirNavUnits = [
    "Unit Mamuju", "Unit Masamba", "Unit Poso", "Unit Toli Toli", "Unit Buol", 
    "Unit Tana Toraja", "Unit Mamasa", "Unit Bone", "Unit Seko", "Unit Rampi", 
    "Unit Bua", "Unit Selayar", "Unit Tojo Una-Una", "Unit Siborong Borong", 
    "Unit Aek Godang", "Unit Lasondre", "Unit Sibolga", "Unit Parapat", 
    "Unit Mandailing Natal", "Unit Tanjung Pandan", "Unit Bandar Lampung", 
    "Unit Muko Muko", "Unit Kerinci", "Unit Muara Bungo", "Unit Lubuk Linggau", 
    "Unit Enggano", "Unit Pagar Alam", "Unit Pekon Serai, Krui Lampung", 
    "Unit Cilacap", "Unit Jember", "Unit Bawean", "Unit Blora", "Unit Kediri", 
    "Unit Waingapu", "Unit Tambolaka", "Unit Pagerungan", "Unit Buleleng", 
    "Unit Datah Dawai", "Unit Melak", "Unit Kota Bangun", "Unit Muara Wahau", 
    "Unit Kutai Timur", "Unit Derawan", "Unit Kiwirok", "Unit Dabra", "Unit Batom", 
    "Unit Senggeh", "Unit Waris (Towe Hitam), Keerom", "Unit Serui", "Unit Numfor", 
    "Unit Kokonao", "Unit Mararena, Sarmi", "Unit Akimuga", "Unit Abmisibil", 
    "Unit Aboy, Peg. Bintang", "Unit Alama, Peg. Bintang", "Unit Jila, Mimika", 
    "Unit Jita, Mimika", "Unit Kapiraya", "Unit Luban", "Unit Okbab", 
    "Unit Potowai, Mimika", "Unit Tsinga, Mimika", "Unit Ubrub, Keerom", 
    "Unit Wangbe, Keerom", "Unit Yuruf, Keerom", "Unit Molof, Keerom", 
    "Unit Lereh, Keerom", "Unit Teraplu", "Unit Kasonaweja", "Unit Sintang", 
    "Unit Putussibau", "Unit Nanga Pinoh", "Unit Sambas", "Unit Harapan, Manis Mata", 
    "Unit Semelagi", "Unit Singkawang", "Unit Meulaboh", "Unit Sinabang", 
    "Unit Takengon", "Unit Tapak Tuan", "Unit Sabang", "Unit Singkil", 
    "Unit Kutacane", "Unit Blang Pidi", "Unit Lhok Seumawe", "Unit Gayo Lues", 
    "Unit Pasir Pangaraian", "Unit Indragiri Hilir", "Unit Dumai", "Unit Pelalawan", 
    "Unit Rokot Sipora", "Unit Pasaman Barat", "Unit Singkep", 
    "Unit Tanjung Balai Karimun", "Unit Bintan", "Unit Anambas (Tanjung Pinang)", 
    "Unit Matak", "Unit Tambelan", "Unit Pondok Cabe", "Unit Pangandaran", 
    "Unit Tasikmalaya", "Unit Kertajati", "Unit Karimun Jawa", "Unit Purbalingga", 
    "Unit Kota Baru", "Unit Kuala Pembuang", "Unit Batu Licin", "Unit Tanjung Warukin", 
    "Unit Muara Teweh", "Unit Kuala Kurun", "Unit Buntok", "Unit Tumbang Samba", 
    "Unit Puruk Cahu", "Unit Nunukan", "Unit Long Bawan", "Unit Long Ampung", 
    "Unit Tanjung Harapan", "Unit Long Layu", "Unit Binuang", "Unit Labuha", 
    "Unit Morotai", "Unit Melonguane", "Unit Kao", "Unit Galela", "Unit Buli Maba", 
    "Unit Sanana", "Unit Tahuna", "Unit Halmahera Tengah", "Unit Manggole Kep. Sola", 
    "Unit Miangas", "Unit Siau", "Unit Bolaang Mongondow", "Unit Pohuwato", 
    "Unit Wakatobi", "Unit Bau Bau", "Unit Kolaka", "Unit Sugimanuru", 
    "Unit Morowali", "Unit Bahodopi", "Unit Lunyuk, Sumbawa", "Unit Maumere", 
    "Unit Larantuka", "Unit Rote", "Unit Sabu", "Unit Bajawa", "Unit Lewoleba", 
    "Unit Atambua", "Unit Ruteng", "Unit Alor", "Unit Pantar", "Unit Dobo", 
    "Unit Saumlaki", "Unit Bandanaira", "Unit Namrole", "Unit Larat", "Unit Wahai", 
    "Unit Amahai", "Unit Moa", "Unit Kuffar", "Unit Namlea", "Unit Kisar", 
    "Unit Tiom", "Unit Karubaga", "Unit Bokondini", "Unit Nop Goliat Dekai, Yahukimo", 
    "Unit Elelim", "Unit Anggruk", "Unit Yalimo", "Unit Holuwun", 
    "Unit Mamberamo Tengah", "Unit Mamit", "Unit Ninia", "Unit Pasema", 
    "Unit Sobaham", "Unit Silimo", "Unit Suru-Suru", "Unit Tolikara", 
    "Unit Mapnduma, Nduga", "Unit Mugi, Nduga", "Unit Paro, Nduga", 
    "Unit Mamberamo Raya", "Unit Kenyam, Nduga", "Unit Illaga", "Unit Bilorai", 
    "Unit Mulia", "Unit Moanamani", "Unit Enarotali", "Unit Waghete, Paniai", 
    "Unit Illu", "Unit Sinak", "Unit Aboyaga, Nabire", "Unit Duma", 
    "Unit Obano, Paniai", "Unit Obano, Intan Jaya", "Unit Botawa", 
    "Unit Beoga, Intan Jaya", "Unit Bilai, Intan Jaya", "Unit Puncak Jaya", 
    "Unit Babo", "Unit Bintuni", "Unit Fak Fak", "Unit Kaimana", "Unit Anggi", 
    "Unit Ayawasi", "Unit Kambuaya", "Unit Inanwatan", 
    "Unit Marinda, Waisai, Raja Ampat", "Unit Teminabuan", "Unit Kebar", 
    "Unit Merdey, Teluk Bintuni", "Unit Kabare", "Unit Wasior", "Unit Ransiki", 
    "Unit Werur, Tambrauw, Papua Barat", "Unit Segun, Sorong", "Unit Ewer", 
    "Unit Kepi", "Unit Bade", "Unit Kimam", "Unit Okaba", "Unit Mindiptanah", 
    "Unit Kamur", "Unit Bomakia", "Unit Senggo", "Unit Manggelum", "Unit Yaniruma", 
    "Unit Wanggemalo", "Unit Iwur", "Unit Aboge", "Unit Wanam", "Unit Borome", 
    "Unit Kebo, Paniai", "Unit Kilmit"
];